version: '3'

networks:
    book-network:

services:

    nginx:
        build:
            context: .
            dockerfile: ./images/nginx.dockerfile
        image: book/nginx
        container_name: book_nginx
        ports:
            - "8080:80"
        volumes:
            - ./www:/var/www/html:delegated
        depends_on:
            - php
            - db
            - redis
        networks:
            - book-network

    db:
        image: mysql:5.7
        container_name: book_db
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'bookdb'
            MYSQL_USER: 'bookuser'
            MYSQL_PASSWORD: 'bookusersecret'
            MYSQL_ROOT_PASSWORD: 'bookrootusersecret'
        restart: always
        networks:
            - book-network

    adminer:
        image: adminer
        container_name: book_adminer
        restart: always
        ports:
            - 8081:8080
        networks:
            - book-network

    php:
        build:
            context: .
            dockerfile: ./images/php.dockerfile
        image: book/php
        container_name: book_php
        volumes:
            - ./www:/var/www/html:delegated
        ports:
            - "9000:9000"
        networks:
            - book-network

    redis:
        image: redis:alpine
        container_name: book_redis
        networks:
            - book-network

